[package]
name = "example-gen"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.87"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
sanitise-file-name = "1.0.0"
skreate = "*"
